#!/bin/bash
#
# bbr from kernel ppa or local module
#


if ! modprobe tcp_bbr; then
    # has no bbr module, upgrade kernel
    wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.12/linux-headers-4.14.12-041412_4.14.12-041412.201801051649_all.deb
    wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.12/linux-headers-4.14.12-041412-generic_4.14.12-041412.201801051649_amd64.deb
    wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.12/linux-image-4.14.12-041412-generic_4.14.12-041412.201801051649_amd64.deb
    dpkg -i ./linux-*.deb
    update-grub
    rm -r ./linux-*.deb
else
    echo "Kernel has bbr support"
fi

_write_sysctl() {
    LINE=$1
    FILE=/etc/sysctl.conf
    if ! grep "$LINE" $FILE > /dev/null 2>&1; then
        echo $LINE >> $FILE
    else
        echo already written: $LINE
    fi
}

_write_sysctl net.core.default_qdisc=fq
_write_sysctl net.ipv4.tcp_congestion_control=bbr
# do not sysctl -p, reboot into new kernel is required to load bbr

