#!/bin/sh

UPDATE='apt update'
INSTALL='apt install -y'

$UPDATE
$INSTALL curl

$INSTALL apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository \
	"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	$(lsb_release -cs) \
	stable"

$UPDATE

$INSTALL docker-ce

# add docker ps/image format
mkdir -p /root/.docker/
cat > /root/.docker/docker.json << _EOF_
{
  "psFormat": "table {{.Names}}\\t{{.Image}}\\t{{.RunningFor}} ago\\t{{.Status}}\\t{{.Command}}",
  "imagesFormat": "table {{.Repository}}\\t{{.Tag}}\\t{{.ID}}\\t{{.Size}}"
}
_EOF_

systemctl enable docker
service docker start

docker info
