#!/bin/sh

UPDATE='apt update'
INSTALL='apt install -y'

$UPDATE
$INSTALL curl

$INSTALL apt-transport-https ca-certificates curl software-properties-common gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
	
echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

$UPDATE
$INSTALL docker-ce docker-ce-cli containerd.io docker-compose-plugin

# add docker ps/image format
mkdir -p /root/.docker/
cat > /root/.docker/docker.json << _EOF_
{
  "psFormat": "table {{.Names}}\\t{{.Image}}\\t{{.RunningFor}} ago\\t{{.Status}}\\t{{.Command}}",
  "imagesFormat": "table {{.Repository}}\\t{{.Tag}}\\t{{.ID}}\\t{{.Size}}"
}
_EOF_

systemctl enable docker
service docker start

docker info
