#!/bin/sh

UPDATE='apt update'
INSTALL='apt install -y'

$UPDATE
$INSTALL curl

$INSTALL apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository \
	"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	$(lsb_release -cs) \
	stable"

$UPDATE

$INSTALL docker-ce

systemctl enable docker
service docker start

docker info
