#!/bin/sh

UPDATE='apt update'
INSTALL='apt install -y'

$UPDATE
$INSTALL \
    build-essential \
	vim \
	curl wget aria2 \
	iftop iotop glances \
	traceroute mtr

# Locale
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
update-locale LC_ALL=en_US.UTF-8

# unattended upgrades
$INSTALL unattended-upgrades
dpkg-reconfigure -f noninteractive unattended-upgrades
