#!/bin/sh

UPDATE='apt update'
INSTALL='apt install -y'
UPGRADE='apt upgrade -y'
AUTOCLEAN='apt autoremove -y'

export DEBIAN_FRONTEND=noninteractive

$UPDATE
$INSTALL \
    build-essential \
    vim \
    curl wget aria2 \
    iftop iotop htop nethogs iperf3 net-tools iputils-ping dnsutils \
    traceroute mtr-tiny \
    jq sed iproute2 cron
$UPGRADE
update-alternatives --set editor $( realpath $( which vim ) )

# Locale
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
update-locale LC_ALL=en_US.UTF-8

# unattended upgrades
$INSTALL unattended-upgrades
dpkg-reconfigure -f noninteractive unattended-upgrades

# upgrade all packages, because I can't be bothered with manual labor
UU_CONF=/etc/apt/apt.conf.d/50unattended-upgrades
sed -i '/Unattended-Upgrade::Allowed-Origins/a \\t"*:*";' $UU_CONF

# create /root/tls/ directory for certs
mkdir -p /root/tls/
