#!/bin/sh

INSTALL='apt install -y'

$INSTALL ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libavfilter-dev libswscale-dev libswresample-dev

git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
( cd nv-codec-headers && make install )
rm -rf nv-codec-headers
