#!/bin/bash

# acme.sh installation target
ACME_SH=~/.acme.sh/acme.sh

# check cloudflare account key
# complaint if not exist

CF_Endpoint=https://api.cloudflare.com/client/v4/

if [ -z "${CF_Email}" -o -z "${CF_Key}" ] && [ -z "${CF_Account_ID}" -o -z "${CF_Token}" ]; then
    echo "Cloudflare credential isn't set"
    echo "Fill in and run either of the followings:"
    echo ""
    echo "  # Global API key"
    echo "  export CF_Email="
    echo "  export CF_Key="
    echo ""
    echo "  # Access Token, requires: Zone.Zone (read), Zone.DNS (read, write)"
    echo "  export CF_Account_ID="
    echo "  export CF_Token="
    exit 2
fi

# assume we are running on .wacky.one
DOMAIN='wacky.one'
FQDN=$( hostname )

while [[ ${FQDN} != *.${DOMAIN} ]] ; do
    echo ""
    echo "<!> fqdn is ${FQDN}, does not match ${DOMAIN}"
    echo "<!> please specify:"
    echo ""
    read -p "fqdn > " FQDN
    echo ""
done

echo "fqdn: ${FQDN}"
echo ""

# check and install prerequisites
which curl > /dev/null && echo 'found: curl' || ./essentials
which jq > /dev/null && echo 'found: jq' || ./essentials
which ip > /dev/null && echo 'found: iproute2' || ./essentials
which nginx > /dev/null && echo 'found: nginx' || ./nginx
which ${ACME_SH} > /dev/null && echo 'found: acme.sh' || ( curl -sL https://get.acme.sh | sh )
echo ""

echo "Change acme.sh CA to letsentrypt"
$ACME_SH --set-default-ca --server letsencrypt

### guess IPv4 IPv6 address
IP4=$( ip -4 addr show scope global | grep -o '\(inet \)[^/]\+' -m 1 | cut -c 6- )
IP6=$( ip -6 addr show scope global | grep -o '\(inet6 \)[^/]\+' -m 1 | cut -c 7- )

[ -z $IP4 ] && echo "ipv4: not found" || echo "ipv4: ${IP4}"
[ -z $IP6 ] && echo "ipv6: not found" || echo "ipv6: ${IP6}"
echo ""

# $1: path (e.g. zones/<id>/dns_records)
# $@: args appended to `curl`
function cf_api () {
    local path="$1"
    shift 1

    if [ -n "${CF_Email}" -a -n "${CF_Key}" ] ; then
        curl -s -H "X-Auth-Email: ${CF_Email}" -H "X-Auth-Key: ${CF_Key}" "${CF_Endpoint}${path}" "$@"
    elif [ -n "${CF_Account_ID}" -a -n "${CF_Token}" ] ; then
        curl -s -H "Authorization: Bearer ${CF_Token}" "${CF_Endpoint}${path}" "$@"
    else
        echo "assertion: not reached."
	echo "either CF_Email + CF_Key or CF_Account_ID + CF_Token needs to be provided"
        exit 2
    fi
}

# probe zone id
ZONE_ID=$( cf_api zones\?name=${DOMAIN} | jq '.result[0].id' )

if [ "${ZONE_ID:-null}" == null ] ; then
    echo "failed to retrieve zone id."
    exit 2
else
    ZONE_ID=$( echo $ZONE_ID | cut -d \" -f 2 )
    echo "zone_id: ${ZONE_ID} / ${DOMAIN}"
fi

# create or update ipv4 / ipv6 record
function set_dns () {
    echo ""

    TYPE=$1
    ADDR=$2
    RESULT_VAR=$3
    RECORD_ID=$( cf_api zones/${ZONE_ID}/dns_records\?type=${TYPE}\&name=${FQDN} | jq .result[0].id )


    PAYLOAD={\"type\":\"${TYPE}\",\"name\":\"${FQDN}\",\"content\":\"${ADDR}\"}

    if [ null == $RECORD_ID ] ; then
        echo "record doesn't exist, creating a new one."
        declare $RESULT_VAR=$( cf_api zones/${ZONE_ID}/dns_records -X POST -H "Content-Type: application/json" --data-ascii ${PAYLOAD} | jq .success )
    else
        RECORD_ID=$( echo $RECORD_ID | cut -d \" -f 2 )
        echo "record found, record_id = ${RECORD_ID} -> ${FQDN}"
        declare $RESULT_VAR=$( cf_api zones/${ZONE_ID}/dns_records/${RECORD_ID} -X PUT -H "Content-Type: application/json" --data-ascii ${PAYLOAD} | jq .success )
    fi

    echo "set_dns: ${TYPE} / ${FQDN} <- ${ADDR}: ${!RESULT_VAR}"
}

[ ! -z $IP4 ] && set_dns A $IP4 IP4_RESULT
[ ! -z $IP6 ] && set_dns AAAA $IP6 IP6_RESULT

# issue acme.sh certs
echo ""

# pass probed ZONE_ID to acme.sh
export CF_Zone_ID="${ZONE_ID}"

mkdir -p ~/tls/
CERT_PATH=~/tls/${FQDN}-cert.pem
KEY_PATH=~/tls/${FQDN}-key.pem

if [ -f $CERT_PATH -a -f $KEY_PATH ]; then
    echo "acme.sh: key cert pair found, renew"
    echo ""
    $ACME_SH --renew --ecc -d ${FQDN}
else
    echo "acme.sh: issue cert"
    echo ""
    while true ; do
        $ACME_SH \
            --issue -d ${FQDN} \
            --dns dns_cf \
            -k ec-256 \
            --key-file ${KEY_PATH} \
            --fullchain-file ${CERT_PATH} \
            --reloadcmd "systemctl reload nginx" \
	    --force

        ACME_RET=$?
        if [ $ACME_RET -eq 0 ] ; then
            break
        else
            echo "acme.sh: wait for DNS propagation, retry after 60s"
            for sec in {1..60} ; do
                echo "."
                sleep 1
            done
            echo ""
        fi
    done
fi

# config nginx
PUBLISH_DIR=/publish
CONF_HTTPS=/etc/nginx/conf.d/${FQDN}.conf
mkdir -p ${PUBLISH_DIR}

cat > ${CONF_HTTPS} <<-_EOF_
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name ${FQDN};

    ssl_certificate /root/tls/${FQDN}-cert.pem;
    ssl_certificate_key /root/tls/${FQDN}-key.pem;

    include /etc/nginx/tls-modern.incl;

    location / {
        root ${PUBLISH_DIR};
        index index.html;
        autoindex on;
    }
}
_EOF_

# check nginx is configured correctly
nginx -t > /dev/null 2>&1
NGINX_CONF_OK=$?
if [ $NGINX_CONF_OK -eq 0 ] ; then
    systemctl reload nginx
else
    echo ""
    echo "nginx: config is incorrect"
    echo "please inspect ${CONF_HTTPS}"
fi
NGINX_CONF_OK=$( [ $NGINX_CONF_OK -eq 0 ] && echo 'ok' || echo 'error' )

# write configured fqdn to acme.sh directory for futher reference
echo "$FQDN" > $( dirname $ACME_SH )/.ok-deploy-fqdn

# print summary
echo ""
echo "ip4: ${IP4}, ${IP4_RESULT}"
echo "ip6: ${IP6}, ${IP6_RESULT}"
echo "nginx: ${NGINX_CONF_OK}"
