#!/bin/bash

PURGE="apt purge -y"

systemctl stop snapd
$PURGE snapd lxd lxd-client

rm -rf /root/snap \
       /snap \
       /var/snap \
       /var/lib/snapd \
       /var/cache/snapd \
       /usr/lib/snapd

cat > /etc/apt/preferences.d/no-snap.pref <<-_EOF_
# To install snapd, specify its version with 'apt install snapd=VERSION'
# where VERSION is the version of the snapd package you want to install.
Package: snapd
Pin: release a=*
Pin-Priority: -10
_EOF_
