#!/bin/bash

set -euo pipefail

PROBE_BIN=/usr/bin/pvedaemon
if ! test -f $PROBE_BIN ; then
  echo "Doesn't look like a PVE installation: ${PROBE_BIN} not found."
  echo "Bail out!"
  exit 1
fi

# Assume it's debian :)
apt update
apt install -y lm-sensors linux-cpupower net-tools lldpd vim git iftop

# LLDP configuration (experimental)
echo 'DAEMON_ARGS="-x -c -s -e"' | tee /etc/default/lldpd
lldpcli configure system interface pattern "*"
systemctl restart lldpd

# Be energy conscious :)
SYSTEMD_POWER_TUNING_SERVICE=ok-deploy-cpu-tuning
cat > /etc/systemd/system/${SYSTEMD_POWER_TUNING_SERVICE}.service <<-_EOF_
[Unit]
Description=CPU Power Tuning

[Service]
Type=oneshot
ExecStart=/usr/bin/cpupower frequency-set -g powersave

[Install]
WantedBy=multi-user.target
_EOF_
systemctl daemon-reload
systemctl enable ${SYSTEMD_POWER_TUNING_SERVICE}
systemctl start ${SYSTEMD_POWER_TUNING_SERVICE}

# Setup PVE checked command auto patch.
#
# Note, patch file contains tabs, so we base64 escape it to prevent most
# editor's tab -> space feature from messing up its content.
PATCH_FILE=/root/.pve_checked_command_patch
{
base64 -d <<-_EOF_
LS0tIHByb3htb3hsaWIuanMJMjAyNS0wOS0yNCAxNzozODo0MC43MDM2NzIxMTkgKzEwMDAKKysr
IC90bXAvYWZ0ZXIuanMJMjAyNS0wOS0yNCAxNzozODozMy4zNjg1ODMzNjggKzEwMDAKQEAgLTYw
MCwzNyArNjAwLDcgQEAKICAgICAgICAgICAgIEV4dC5Nc2cuYWxlcnQoZ2V0dGV4dCgnRXJyb3In
KSwgcmVzLmh0bWxTdGF0dXMgfHwgcmVzLnJlc3VsdC5tZXNzYWdlKSwKIAogICAgICAgICBjaGVj
a2VkX2NvbW1hbmQ6IGZ1bmN0aW9uIChvcmlnX2NtZCkgewotICAgICAgICAgICAgUHJveG1veC5V
dGlscy5BUEkyUmVxdWVzdCh7Ci0gICAgICAgICAgICAgICAgdXJsOiAnL25vZGVzL2xvY2FsaG9z
dC9zdWJzY3JpcHRpb24nLAotICAgICAgICAgICAgICAgIG1ldGhvZDogJ0dFVCcsCi0gICAgICAg
ICAgICAgICAgZmFpbHVyZTogZnVuY3Rpb24gKHJlc3BvbnNlLCBvcHRzKSB7Ci0gICAgICAgICAg
ICAgICAgICAgIEV4dC5Nc2cuYWxlcnQoZ2V0dGV4dCgnRXJyb3InKSwgcmVzcG9uc2UuaHRtbFN0
YXR1cyk7Ci0gICAgICAgICAgICAgICAgfSwKLSAgICAgICAgICAgICAgICBzdWNjZXNzOiBmdW5j
dGlvbiAocmVzcG9uc2UsIG9wdHMpIHsKLSAgICAgICAgICAgICAgICAgICAgbGV0IHJlcyA9IHJl
c3BvbnNlLnJlc3VsdDsKLSAgICAgICAgICAgICAgICAgICAgaWYgKAotICAgICAgICAgICAgICAg
ICAgICAgICAgcmVzID09PSBudWxsIHx8Ci0gICAgICAgICAgICAgICAgICAgICAgICByZXMgPT09
IHVuZGVmaW5lZCB8fAotICAgICAgICAgICAgICAgICAgICAgICAgIXJlcyB8fAotICAgICAgICAg
ICAgICAgICAgICAgICAgcmVzLmRhdGEuc3RhdHVzLnRvTG93ZXJDYXNlKCkgIT09ICdhY3RpdmUn
Ci0gICAgICAgICAgICAgICAgICAgICkgewotICAgICAgICAgICAgICAgICAgICAgICAgRXh0Lk1z
Zy5zaG93KHsKLSAgICAgICAgICAgICAgICAgICAgICAgICAgICB0aXRsZTogZ2V0dGV4dCgnTm8g
dmFsaWQgc3Vic2NyaXB0aW9uJyksCi0gICAgICAgICAgICAgICAgICAgICAgICAgICAgaWNvbjog
RXh0Lk1zZy5XQVJOSU5HLAotICAgICAgICAgICAgICAgICAgICAgICAgICAgIG1lc3NhZ2U6IFBy
b3htb3guVXRpbHMuZ2V0Tm9TdWJLZXlIdG1sKHJlcy5kYXRhLnVybCksCi0gICAgICAgICAgICAg
ICAgICAgICAgICAgICAgYnV0dG9uczogRXh0Lk1zZy5PSywKLSAgICAgICAgICAgICAgICAgICAg
ICAgICAgICBjYWxsYmFjazogZnVuY3Rpb24gKGJ0bikgewotICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICBpZiAoYnRuICE9PSAnb2snKSB7Ci0gICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICByZXR1cm47Ci0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIH0KLSAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgb3JpZ19jbWQoKTsKLSAgICAgICAgICAgICAg
ICAgICAgICAgICAgICB9LAotICAgICAgICAgICAgICAgICAgICAgICAgfSk7Ci0gICAgICAgICAg
ICAgICAgICAgIH0gZWxzZSB7Ci0gICAgICAgICAgICAgICAgICAgICAgICBvcmlnX2NtZCgpOwot
ICAgICAgICAgICAgICAgICAgICB9Ci0gICAgICAgICAgICAgICAgfSwKLSAgICAgICAgICAgIH0p
OworICAgICAgICAgICAgb3JpZ19jbWQoKTsKICAgICAgICAgfSwKIAogICAgICAgICBhc3NlbWJs
ZV9maWVsZF9kYXRhOiBmdW5jdGlvbiAodmFsdWVzLCBkYXRhKSB7Cg==
_EOF_
} | cat > $PATCH_FILE

APT_HOOK=/root/.pve_checked_command_apt_hook
cat > $APT_HOOK <<-_EOF_
#!/usr/bin/bash
FILE=/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
if grep -q 'MAGIC:CHECK_COMMAND_PATCHED' \$FILE ; then 
  echo "PVE checked_command already patched"
else
  patch \$FILE $PATCH_FILE 
fi
_EOF_
chmod +x $APT_HOOK

cat > /etc/apt/apt.conf.d/99okdeploy_checked_command_patch <<-_EOF_
DPkg::Post-Invoke {"$APT_HOOK";}
_EOF_

export DEBIAN_FRONTEND=noninteractive
apt update
apt upgrade -y
